import {
  Box,
  Button,
  Container,
  Divider,
  Icon,
  Stack,
  Text,
  useColorModeValue,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import Card from "../components/card";
import SlideShow from "../components/slide-show";
import AOS from "aos";
import { useEffect } from "react";
import MainCard from "../components/main-card";
import { MdGroups } from "react-icons/md";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    AOS.init();
  }, []);
  return (
    <Box className="p-2">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <SlideShow />

      <Container maxW="container.xl" className="p-5">
        <Box className="mt-10 mb-24">
          <Box className="grid grid-col-1 md:grid-cols-2">
            <Box
              className="p-4 rounded-md m-2"
              bg={useColorModeValue(
                "rgb(11,25,51,0.8)",
                "rgb(232,240,242,0.8)"
              )}
              color={useColorModeValue("rgb(232,240,242)", "rgb(11,25,51)")}
            >
              <Text className="text-2xl font-bold mb-4">WHY ACM?</Text>
              <Text>
                <strong>NUCES ACM Lahore</strong> is the tech-focused computer
                science society at FAST Lahore responsible for organizing
                workshops, seminars, gaming competitions, quizzes, programming
                competitions. Our student chapter is licensed and affiliated
                with the International Association of Computing Machinery
              </Text>
            </Box>
            <MainCard
              title="Most Attractive IT WEEK"
              bold="ACM"
              desc=" is one of the best Society for the person who want to learn different skills. In our IT week, we provide different opportunities to our participants to learn and to develop their skills."
            />
            <MainCard
              title="Legacy of Past Years"
              bold="NUCES ACM Lahore"
              desc=" is responsible for holding events like Geek Week, workshops, seminars and competitions."
            />
            <MainCard
              title="Annual Tridition"
              bold="Geek Week is NUCES ACM’s"
              desc=" annual flagship event. It’s a place where geeks and techies from all over the country gather to impart and gain knowledge, and also to test themselves. The tech-oriented event is no doubt beneficial to all aspiring geeks!"
            />
          </Box>
          <MainCard
            title="Our Initiative"
            bold="ACM International"
            desc="  is the world’s largest educational and scientific computing society, delivering resources that advance computing as a science and a profession. ACM provides the computing field’s premier digital library."
          />
        </Box>
        <Divider />
        <Box className="grid grid-cols-1 md:grid-cols-2 items-center my-24">
          <Box className="mb-10 md:mb-0 mx-auto">
            <Image src="/Images/cover.jpg" height="480" width="360" alt="" />
          </Box>
          <Box className="mx-auto">
            <Text>
              We’re proud to announce that we have bagged the coveted ACM
              International Chapter Excellence Award for “Outstanding Chapter
              Activities” from ACM – Association for Computing Machinery ACM
              Student Chapters around the world compete for these excellence
              awards and we’re stoked to be awarded for this category. We thank
              our advisors: Dr. Muhammad Kamran Lodhi and Dr. Mubasher Baig, our
              mentors, senior exe-members that will depart this semester and of
              course, all the participants. We would also like to thank our
              outreach partners: NUST ACM Student Chapter, Developer Student
              Club FAST Lahore, Developer Student Club – NUST, our media
              partner: NMG – Nuces Media Group, and FAST Music Society for
              jazzing up Geek Week ’20! It goes without saying that we’re also
              extremely grateful to our guests for making Geek Week ’20 the
              stellar success that it was! We hope to make the year 2020-21 even
              better by setting the bar higher than before and beating the
              benchmarks we set for ourselves last year!
            </Text>
          </Box>
        </Box>
        <Divider />
        <Box className="mt-24 mb-12 flex justify-center">
          <Button
            onClick={() => router.push("/teams")}
            bg="#697bb0"
            //colorScheme="blue"
            leftIcon={<MdGroups size="30" />}
            className="hover:text-[#697bb0] hover:bg-slate-400 shadow-2xl"
            //on_hover
          >
            Our Exective Team
          </Button>
        </Box>
      </Container>
    </Box>
  );
}
